// Code generated by mockery v2.14.0. DO NOT EDIT.

package ucmock

import (
	entity "balance_api/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Balance is an autogenerated mock type for the Balance type
type Balance struct {
	mock.Mock
}

// ChangeOrderStatus provides a mock function with given fields: ctx, order
func (_m *Balance) ChangeOrderStatus(ctx context.Context, order entity.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *Balance) CreateOrder(ctx context.Context, order entity.Order) error {
	ret := _m.Called(ctx, order)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Balance) GetByID(ctx context.Context, id int) (entity.Balance, error) {
	ret := _m.Called(ctx, id)

	var r0 entity.Balance
	if rf, ok := ret.Get(0).(func(context.Context, int) entity.Balance); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entity.Balance)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields: ctx, history
func (_m *Balance) GetHistory(ctx context.Context, history entity.History) (entity.History, error) {
	ret := _m.Called(ctx, history)

	var r0 entity.History
	if rf, ok := ret.Get(0).(func(context.Context, entity.History) entity.History); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Get(0).(entity.History)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.History) error); ok {
		r1 = rf(ctx, history)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReportDir provides a mock function with given fields:
func (_m *Balance) GetReportDir() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Increase provides a mock function with given fields: ctx, balance
func (_m *Balance) Increase(ctx context.Context, balance entity.Balance) error {
	ret := _m.Called(ctx, balance)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Balance) error); ok {
		r0 = rf(ctx, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateReport provides a mock function with given fields: ctx, year, month
func (_m *Balance) UpdateReport(ctx context.Context, year int, month int) (string, error) {
	ret := _m.Called(ctx, year, month)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, int, int) string); ok {
		r0 = rf(ctx, year, month)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, year, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBalance interface {
	mock.TestingT
	Cleanup(func())
}

// NewBalance creates a new instance of Balance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBalance(t mockConstructorTestingTNewBalance) *Balance {
	mock := &Balance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
